// A catalogue of projects a user can install as a dependency. Each entry is a
// Metacello baseline (the wider Smalltalk world ships Seaside/Grease/Zinc/… as
// Metacello, not Rowan) — Jasper loads the baseline into the stone and adopts it
// into a Rowan project. Seeded from the GsDevKit catalogue
// (gsdevkit.github.io/GsDevKit_home, gh-pages) and extensible by the user.
//
// The seed was generated by fetching the GsDevKit `.ston` entries, mapping their
// TDProjectSpecEntryDefinition fields (projectUrl / baseline / repository /
// loads), curating to installable libraries (dropping tooling: GsDevKit_home,
// Tode, SmalltalkCI, Metacello, GsUpgrader, …), and pinning Seaside to its
// latest release. To refresh it, re-run that fetch+map against gh-pages.

export interface RowanCatalogEntry {
  name: string;
  // Short human blurb (may be empty for now).
  description: string;
  // The project's home page, for reference/links (may be empty).
  projectUrl: string;
  // The Metacello baseline name (e.g. 'Seaside3').
  baseline: string;
  // The Metacello repository URL; its `:branch|tag` segment pins the version.
  repository: string;
  // Metacello load groups (e.g. ['default'] or ['Core']).
  loads: string[];
}

export const CATALOG_SEED: readonly RowanCatalogEntry[] = [
  {
    name: 'Seaside',
    baseline: 'Seaside3',
    repository: 'github://SeasideSt/Seaside:v3.6.0/repository',
    loads: ['Welcome', 'Development', 'Zinc Project', 'Examples'],
    projectUrl: 'https://github.com/SeasideSt/Seaside',
    description: 'The Seaside web framework (via Metacello baseline).',
  },
  {
    name: 'BitmapCharacterSet',
    baseline: 'BitmapCharacterSet',
    repository: 'github://GsDevKit/BitmapCharacterSet:gemstone/filetree',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/BitmapCharacterSet',
    description: '',
  },
  {
    name: 'BpmFlow',
    baseline: 'BpmFlow',
    repository: 'github://brunobuzzi/BpmFlow:master/repository',
    loads: ['default'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'Cryptography',
    baseline: 'Cryptography',
    repository: 'github://GsDevKit/Cryptography:master/repository',
    loads: ['Cryptography'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'FileTree',
    baseline: 'FileTree',
    repository: 'github://dalehenrich/filetree:gemstone2.4/repository/',
    loads: ['default'],
    projectUrl: 'https://github.com/dalehenrich/filetree',
    description: '',
  },
  {
    name: 'Flow',
    baseline: 'Flow',
    repository: 'github://GsDevKit/flow:master/backend/src',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/flow',
    description: '',
  },
  {
    name: 'GLASS1',
    baseline: 'GLASS1',
    repository: 'github://glassdb/glass:master/repository',
    loads: ['default'],
    projectUrl: 'https://github.com/glassdb/glass',
    description: '',
  },
  {
    name: 'Grease',
    baseline: 'Grease',
    repository: 'github://GsDevKit/Grease:master/repository',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/Grease',
    description: '',
  },
  {
    name: 'GsApplicationTools',
    baseline: 'GsApplicationTools',
    repository: 'github://GsDevKit/gsApplicationTools:master/repository',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/gsApplicationTools',
    description: '',
  },
  {
    name: 'Magritte3',
    baseline: 'Magritte3',
    repository: 'github://GsDevKit/Magritte3:master/repository',
    loads: ['Core'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'Mapless',
    baseline: 'Mapless',
    repository: 'github://GsDevKit/Mapless:master/src',
    loads: ['Core'],
    projectUrl: 'https://github.com/GsDevKit/Mapless',
    description: '',
  },
  {
    name: 'MongoTalk',
    baseline: 'MongoTalk',
    repository: 'github://dalehenrich/mongotalk:tugrik/mc',
    loads: ['Core', 'Tests'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'NeoJSON',
    baseline: 'NeoJSON',
    repository: 'github://GsDevKit/NeoJSON:gs_master/repository',
    loads: ['Core'],
    projectUrl: 'https://github.com/GsDevKit/NeoJSON',
    description: '',
  },
  {
    name: 'Obex',
    baseline: 'Obex',
    repository: 'github://dalehenrich/obex:master/repository',
    loads: ['Core'],
    projectUrl: 'https://github.com/dalehenrich/obex',
    description: '',
  },
  {
    name: 'OrbeonPersistenceLayer',
    baseline: 'OrbeonPersistenceLayer',
    repository: 'github://brunobuzzi/OrbeonPersistenceLayer:master/repository',
    loads: ['default'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'OrderPreservingDictionary',
    baseline: 'OrderPreservingDictionary',
    repository: 'github://GsDevKit/OrderPreservingDictionary:gemstone/filetree',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/OrderPreservingDictionary',
    description: '',
  },
  {
    name: 'Parasol',
    baseline: 'Parasol',
    repository: 'github://SeasideSt/Parasol:master/repository',
    loads: ['default'],
    projectUrl: 'https://github.com/SeasideSt/Parasol',
    description: '',
  },
  {
    name: 'PharoCompatibility',
    baseline: 'PharoCompatibility',
    repository: 'github://glassdb/PharoCompatibility:master/repository',
    loads: ['default'],
    projectUrl: 'https://github.com/glassdb/PharoCompatibility',
    description: '',
  },
  {
    name: 'PharoGs',
    baseline: 'PharoGs',
    repository: 'github://dalehenrich/PharoGs:gs/src',
    loads: ['Tests'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'RB',
    baseline: 'RB',
    repository: 'github://dalehenrich/rb:master/repository/',
    loads: ['AST-Core'],
    projectUrl: 'https://github.com/dalehenrich/rb',
    description: '',
  },
  {
    name: 'ServiceVM',
    baseline: 'ServiceVM',
    repository: 'github://GsDevKit/ServiceVM:master/repository',
    loads: ['Core', 'Example', 'Tests'],
    projectUrl: 'https://github.com/GsDevKit/ServiceVM',
    description: '',
  },
  {
    name: 'SIXX',
    baseline: 'SIXX',
    repository: 'github://glassdb/SIXX:master/repository',
    loads: [],
    projectUrl: 'https://github.com/glassdb/SIXX',
    description: '',
  },
  {
    name: 'Ston',
    baseline: 'Ston',
    repository: 'github://GsDevKit/ston:gemstone/repository',
    loads: ['Core'],
    projectUrl: 'https://github.com/GsDevKit/ston',
    description: '',
  },
  {
    name: 'Tugrik',
    baseline: 'Tugrik',
    repository: 'github://dalehenrich/Tugrik:master/repository',
    loads: ['default'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'Voyage',
    baseline: 'Voyage',
    repository: 'github://dalehenrich/voyage:tugrik/mc',
    loads: ['tugrik', 'tugrik tests'],
    projectUrl: '',
    description: '',
  },
  {
    name: 'XMLParser',
    baseline: 'XMLParser',
    repository: 'github://GsDevKit/XML-XMLParser:gemstone/filetree',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/XML-XMLParser',
    description: '',
  },
  {
    name: 'XMLWriter',
    baseline: 'XMLWriter',
    repository: 'github://GsDevKit/XML-XMLWriter:gemstone/filetree',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/XML-XMLWriter',
    description: '',
  },
  {
    name: 'XPath',
    baseline: 'XPath',
    repository: 'github://GsDevKit/XML-XPath:gemstone/filetree',
    loads: ['default'],
    projectUrl: 'https://github.com/GsDevKit/XML-XPath',
    description: '',
  },
  {
    name: 'ZincHTTPComponents',
    baseline: 'ZincHTTPComponents',
    repository: 'github://GsDevKit/zinc:2.4.3.?/repository',
    loads: ['Core'],
    projectUrl: 'https://github.com/GsDevKit/zinc',
    description: '',
  },
  {
    name: 'Zodiac',
    baseline: 'Zodiac',
    repository: 'github://GsDevKit/zodiac:gs_master/repository/',
    loads: ['Core', 'Tests', 'Extras'],
    projectUrl: 'https://github.com/GsDevKit/zodiac',
    description: '',
  },
];

// The full catalogue: the seed plus the user's own entries. A user entry with
// the same name overrides the seed (so the seed can be tweaked locally). Pure —
// the caller supplies the user entries (persisted in globalState).
export function mergeCatalog(userEntries: readonly RowanCatalogEntry[] = []): RowanCatalogEntry[] {
  const byName = new Map<string, RowanCatalogEntry>();
  for (const e of CATALOG_SEED) byName.set(e.name, e);
  for (const e of userEntries) byName.set(e.name, e);
  return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name));
}
