import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export const store = new Vuex.Store({
  strict: process.env.NODE_ENV !== 'production',
  state: {
    appTitle: 'Jasper',
    gemConfig: [],
    gemUser: [],
    gemVersion: [],
    gemsData: [],
    gemsHeader: [],
    stats: 'statistics',
    user: null,
    error: null,
    loading: false,
    isAuthenticated: false,
    stoneConfig: [],
    stoneHistory: '',
    stoneVersion: []
  },
  mutations: {
    gemConfig (state, payload) {
      state.gemConfig = payload
    },
    gemUser (state, payload) {
      state.gemUser = payload
    },
    gemVersion (state, payload) {
      state.gemVersion = payload
    },
    gemsData (state, payload) {
      state.gemsData = payload
    },
    gemsHeader (state, payload) {
      state.gemsHeader = payload
    },
    stoneConfig (state, payload) {
      state.stoneConfig = payload
    },
    stoneHistory (state, payload) {
      state.stoneHistory = payload
    },
    stoneVersion (state, payload) {
      state.stoneVersion = payload
    },
    userSignIn (state, payload) {
      state.isAuthenticated = true
    },
    userSignOut (state, payload) {
      state.isAuthenticated = false
    },
    userSignUp (state, payload) {
      state.isAuthenticated = true
    }
  },
  actions: {
  },
  getters: {
  }
})

store.commit('stoneHistory',
  'GemStone/S64 v3.4.1 kernel classes filein completed at 02/01/2018 11:32:30')
store.commit('stoneVersion', [
  ['cpuArchitecture', 'x86-64'],
  ['cpuKind', 'x86_64'],
  ['gsBuildArchitecture', 'Darwin (Mac)'],
  ['gsBuildDate', 'Tue Jan  2 11:10:18 2018'],
  ['gsBuildSerialNum', 'gss64_3_4_x_branch-43410'],
  ['gsBuildType', 'FAST'],
  ['gsRelease', '3.4.1'],
  ['gsVersion', '3.4.1'],
  ['nodeName', 'vienna.local'],
  ['osName', 'Darwin'],
  ['osRelease', '17.6.0'],
  ['osVersion', 'Darwin Kernel Version 17.6.0, Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64'],
  ['processId', 26233],
  ['processorCount', 4]
])
store.commit('stoneConfig', [
  ['CONFIG_WARNINGS_FATAL', false],
  ['DBF_ALLOCATION_MODE', 'SEQUENTIAL'],
  ['DBF_EXTENT_NAMES', '/Users/jfoster/Library/GemStone/db4/data/extent0.dbf'],
  ['DBF_EXTENT_SIZES', -1],
  ['DBF_PRE_GROW', false],
  ['DBF_SCRATCH_DIR', '/Users/jfoster/Library/GemStone/db4/data/'],
  ['DUMP_OPTIONS', true],
  ['KEYFILE', '$GEMSTONE/seaside/etc/gemstone.key'],
  ['LOG_WARNINGS', true],
  ['LogOriginTime', 1531194891],
  ['SessionInBackup', -1],
  ['SHR_NUM_FREE_FRAME_SERVERS', 1],
  ['SHR_PAGE_CACHE_LARGE_MEMORY_PAGE_POLICY', 0],
  ['SHR_PAGE_CACHE_LARGE_MEMORY_PAGE_SIZE_MB', 0],
  ['SHR_PAGE_CACHE_LOCKED', false],
  ['SHR_PAGE_CACHE_NUM_PROCS', 51],
  ['SHR_PAGE_CACHE_NUM_SHARED_COUNTERS', 1900],
  ['SHR_PAGE_CACHE_PERMISSIONS', 432],
  ['SHR_PAGE_CACHE_SIZE_KB', 100000],
  ['SHR_SPIN_LOCK_COUNT', 5000],
  ['SHR_TARGET_FREE_FRAME_COUNT', -1],
  ['SHR_WELL_KNOWN_PORT_NUMBER', 0],
  ['ShrPcTargetPercentDirty', 20],
  ['SpinLockCount', 5000],
  ['STN_ADMIN_GC_SESSION_ENABLED', true],
  ['STN_AIO_WAIT_TIME', 25],
  ['STN_ALLOCATE_HIGH_OOPS', 0],
  ['STN_ALLOW_NFS_EXTENTS', true],
  ['STN_ALLOW_NO_SESSION_INIT', false],
  ['STN_CACHE_WARMER', 0],
  ['STN_CACHE_WARMER_ARGS', ''],
  ['STN_CACHE_WARMER_SESSIONS', 0],
  ['STN_CACHE_WARMER_WAIT_MODE', 1],
  ['STN_CHECKPOINT_INTERVAL', 300],
  ['STN_COMMIT_QUEUE_THRESHOLD', -1],
  ['STN_COMMIT_RECORD_BM_CACHING', true],
  ['STN_COMMIT_RECORD_QUEUE_SIZE', 40],
  ['STN_COMMIT_TOKEN_TIMEOUT', 0],
  ['STN_COMMITS_ASYNC', false],
  ['STN_CR_BACKLOG_THRESHOLD', 80],
  ['STN_DISABLE_LOGIN_FAILURE_LIMIT', 15],
  ['STN_DISABLE_LOGIN_FAILURE_TIME_LIMIT', 15],
  ['STN_DISKFULL_TERMINATION_INTERVAL', 3],
  ['STN_EPOCH_GC_ENABLED', false],
  ['STN_EXTENT_IO_FLAGS', 0],
  ['STN_FREE_FRAME_CACHE_SIZE', -1],
  ['STN_FREE_SPACE_THRESHOLD', 0],
  ['STN_GEM_ABORT_TIMEOUT_SECONDS', 60],
  ['STN_GEM_LOSTOT_TIMEOUT', 60],
  ['STN_GEM_PGSVR_CONNECT_TIMEOUT', 20],
  ['STN_GEM_PRIVATE_PGSVR_ENABLED', false],
  ['STN_GEM_TIMEOUT', 0],
  ['STN_GROUP_COMMITS', 10],
  ['STN_HALT_ON_FATAL_ERR', false],
  ['STN_LISTENING_ADDRESSES', '::'],
  ['STN_LOG_IO_FLAGS', 0],
  ['STN_LOG_LOGIN_FAILURE_LIMIT', 10],
  ['STN_LOG_LOGIN_FAILURE_TIME_LIMIT', 10],
  ['STN_LOGIN_LOG_DIR', ''],
  ['STN_LOGIN_LOG_ENABLED', false],
  ['STN_LOGIN_LOG_HALT_ON_ERROR', false],
  ['STN_LOGIN_LOG_MAX_SIZE', 0],
  ['STN_LOOP_NO_WORK_THRESHOLD', 0],
  ['STN_MAX_AIO_RATE', 3000],
  ['STN_MAX_AIO_REQUESTS', 51],
  ['STN_MAX_GC_RECLAIM_SESSIONS', 0],
  ['STN_MAX_LOGIN_LOCK_SPIN_COUNT', 100],
  ['STN_MAX_REMOTE_CACHES', 255],
  ['STN_MAX_SESSIONS', 40],
  ['STN_MAX_SLEEP_TIME', 1000],
  ['STN_MAX_VOTING_SESSIONS', 100],
  ['STN_NUM_AIO_WRITE_THREADS', 4],
  ['STN_NUM_GC_RECLAIM_SESSIONS', 1],
  ['STN_NUM_LOCAL_AIO_SERVERS', 1],
  ['STN_OBJ_LOCK_TIMEOUT', 0],
  ['STN_PAGE_MGR_COMPRESSION_ENABLED', false],
  ['STN_PAGE_MGR_MAX_WAIT_TIME', 200],
  ['STN_PAGE_MGR_PRINT_TIMEOUT_THRESHOLD', 5],
  ['STN_PAGE_MGR_REMOVE_MAX_PAGES', 16384],
  ['STN_PAGE_MGR_REMOVE_MIN_PAGES', 40],
  ['STN_PRIVATE_PAGE_CACHE_KB', 2000],
  ['STN_REMOTE_CACHE_PGSVR_TIMEOUT', 15],
  ['STN_REMOTE_CACHE_STARTUP_TIMEOUT', 60],
  ['STN_REMOTE_CACHE_TIMEOUT', 5],
  ['STN_SHR_TARGET_PERCENT_DIRTY', 20],
  ['STN_SIGNAL_ABORT_AGGRESSIVE', 0],
  ['STN_SIGNAL_ABORT_CR_BACKLOG', 20],
  ['STN_SMC_SPIN_LOCK_COUNT', 5000],
  ['STN_STATMONITOR_ARGS', ''],
  ['STN_STONE_CACHE_STARTUP_TIMEOUT', 60],
  ['STN_SYMBOL_GC_ENABLED', false],
  ['STN_SYMBOL_GEM_TEMPOBJ_CACHE_SIZE', 20480],
  ['STN_TRAN_FULL_LOGGING', true],
  ['STN_TRAN_LOG_DEBUG_LEVEL', 0],
  ['STN_TRAN_LOG_DIRECTORIES', ['/Users/jfoster/Library/GemStone/db4/data/', '/Users/jfoster/Library/GemStone/db4/data/']],
  ['STN_TRAN_LOG_LIMIT', 1000],
  ['STN_TRAN_LOG_PREFIX', 'tranlog'],
  ['STN_TRAN_LOG_SIZES', [1000, 1000]],
  ['STN_TRANQ_TO_RUNQ_THRESHOLD', 2],
  ['STN_WELL_KNOWN_PORT_NUMBER', 0],
  ['StnAdminGcSessionEnabled', true],
  ['StnAllowNoSessionInit', 0],
  ['StnCheckpointInterval', 300],
  ['StnCommitQueueThreshold', 4294967295],
  ['StnCrBacklogThreshold', 80],
  ['StnCurrentTranLogDirId', 0],
  ['StnCurrentTranLogNames', '/Users/jfoster/Library/GemStone/db4/data/tranlog1.dbf'],
  ['StnDisableLoginFailureLimit', 15],
  ['StnDisableLoginFailureTimeLimit', 15],
  ['StnDiskfullTerminationInterval', 3],
  ['StnEpochGcEnabled', false],
  ['StnFreeSpaceThreshold', 0],
  ['StnFreeSpaceThresholdMb', 5],
  ['StnGemAbortTimeoutSeconds', 60],
  ['StnGemLostOtTimeout', 60],
  ['StnGemPgsvrConnectTimeout', 20],
  ['StnGemPrivatePgsvrEnabled', 0],
  ['StnGemTimeout', 0],
  ['StnHaltOnFatalErr', false],
  ['StnLogFileName', '/Users/jfoster/Library/GemStone/db4/log/gs64stone4.log'],
  ['StnLogGemErrors', false],
  ['StnLoginsSuspended', false],
  ['StnLogLoginFailureLimit', 10],
  ['StnLogLoginFailureTimeLimit', 10],
  ['StnLoopNoWorkThreshold', 0],
  ['StnMaxLoginLockSpinCount', 100],
  ['StnMaxReposSize', 655360],
  ['StnMaxSessions', 10],
  ['StnMaxVotingSessions', 100],
  ['StnMntMaxAioRate', 3000],
  ['StnNumGcReclaimSessions', 1],
  ['StnObjLockTimeout', 0],
  ['StnPageMgrCompressionEnabled', false],
  ['StnPageMgrMaxWaitTime', 200],
  ['StnPageMgrPrintTimeoutThreshold', 5],
  ['StnPageMgrRemoveMaxPages', 16384],
  ['StnPageMgrRemoveMinPages', 40],
  ['StnRemoteCachePgsvrTimeout', 15],
  ['StnRemoteCacheStartupTimeout', 60],
  ['StnRemoteCacheTimeout', 5],
  ['StnSignalAbortAggressive', 0],
  ['StnSignalAbortCrBacklog', 20],
  ['StnSmcSpinLockCount', 5000],
  ['StnStandbyRole', 'none'],
  ['StnSunsetDate', 0],
  ['StnSymbolGcEnabled', false],
  ['StnSymbolGemTocSize', 20480],
  ['StnTranLogDebugLevel', 0],
  ['StnTranLogLimit', 1000],
  ['StnTranLogOriginTime', 1531194891],
  ['StnTranqToRunqThreshold', 2]
])

store.commit('gemUser', [
  ['userId', 'DataCurator'],
  ['stoneHost', 'localhost'],
  ['stoneName', 'gs64stone4'],
  ['stoneSession', 5],
  ['gemHost', 'vienna'],
  ['netService', 'netldi4'],
  ['netTask', 'gemnetobject'],
  ['gciVersion', '64-bit 3.4.1'],
  ['gciSession', 1],
  ['stoneSerial', 21],
  ['logPath', '/Users/jfoster/Library/GemStone/db4/log']
])
store.commit('gemVersion', [
  ['cpuArchitecture', 'x86-64'],
  ['cpuKind', 'x86_64'],
  ['gsBuildArchitecture', 'Darwin (Mac)'],
  ['gsBuildDate', 'Tue Jan  2 11:10:18 2018'],
  ['gsBuildSerialNum', 'gss64_3_4_x_branch-43410'],
  ['gsBuildType', 'FAST'],
  ['gsRelease', '3.4.1'],
  ['gsVersion', '3.4.1'],
  ['nodeName', 'vienna.local'],
  ['osName', 'Darwin'],
  ['osRelease', '17.6.0'],
  ['osVersion', 'Darwin Kernel Version 17.6.0, Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64'],
  ['processId', 38810],
  ['processorCount', 4]
])
store.commit('gemConfig', [
  ['CONFIG_WARNINGS_FATAL', false],
  ['DUMP_OPTIONS', true],
  ['GEM_ABORT_MAX_CRS', 0],
  ['GEM_CACHE_WARMER_ARGS', ''],
  ['GEM_CACHE_WARMER_MID_CACHE_ARGS', ''],
  ['GEM_COMPRESS_TRANLOG_RECORDS', true],
  ['GEM_FREE_FRAME_CACHE_SIZE', -1],
  ['GEM_FREE_FRAME_LIMIT', -1],
  ['GEM_FREE_PAGEIDS_CACHE', 200],
  ['GEM_HALT_ON_ERROR', -1],
  ['GEM_KEEP_MIN_SOFTREFS', 0],
  ['GEM_KERBEROS_KEYTAB_FILE', ''],
  ['GEM_KEYRING_DIRS', ''],
  ['GEM_MAX_SMALLTALK_STACK_DEPTH', 1000],
  ['GEM_NATIVE_CODE_ENABLED', 2],
  ['GEM_PGSVR_COMPRESS_PAGE_TRANSFERS', false],
  ['GEM_PGSVR_FREE_FRAME_CACHE_SIZE', -1],
  ['GEM_PGSVR_FREE_FRAME_LIMIT', -1],
  ['GEM_PGSVR_UPDATE_CACHE_ON_READ', false],
  ['GEM_PGSVR_USE_SSL', false],
  ['GEM_PRIVATE_PAGE_CACHE_KB', 983040],
  ['GEM_READ_AUTH_ERR_STUBS', false],
  ['GEM_REPOSITORY_IN_MEMORY', false],
  ['GEM_RPC_KEEPALIVE_INTERVAL', 0],
  ['GEM_RPC_USE_SSL', true],
  ['GEM_RPCGCI_TIMEOUT', 0],
  ['GEM_SOFTREF_CLEANUP_PERCENT_MEM', 50],
  ['GEM_STATMONITOR_ARGS', ''],
  ['GEM_STATMONITOR_MID_CACHE_ARGS', ''],
  ['GEM_TEMPOBJ_AGGRESSIVE_STUBBING', true],
  ['GEM_TEMPOBJ_CACHE_SIZE', 153600000],
  ['GEM_TEMPOBJ_CONSECUTIVE_MARKSWEEP_LIMIT', 50],
  ['GEM_TEMPOBJ_MESPACE_SIZE', 0],
  ['GEM_TEMPOBJ_OOMSTATS_CSV', false],
  ['GEM_TEMPOBJ_OOPMAP_SIZE', 0],
  ['GEM_TEMPOBJ_POMGEN_PRUNE_ON_VOTE', 90],
  ['GEM_TEMPOBJ_POMGEN_SCAVENGE_INTERVAL', 1800],
  ['GEM_TEMPOBJ_POMGEN_SIZE', 0],
  ['GEM_TEMPOBJ_SCOPES_SIZE', 2000],
  ['GEM_TEMPOBJ_START_ADDR', 0],
  ['GemAbortMaxCrs', 0],
  ['GemCompressTranlogRecords', true],
  ['GemConvertArrayBuilder', false],
  ['GemDropCommittedExportedObjs', false],
  ['GemExceptionSignalCapturesStack', false],
  ['GemFreeFrameLimit', 625],
  ['GemFreePageIdsCache', 200],
  ['GemHaltOnError', 0],
  ['GemKeepMinSoftRefs', 0],
  ['GemKeyRingDirs', ''],
  ['GemNativeCodeEnabled', 2],
  ['GemPgsvrCompressPageTransfers', false],
  ['GemPgsvrUpdateCacheOnRead', false],
  ['GemPomGenPruneOnVote', 90],
  ['GemReadAuthErrStubs', false],
  ['GemRepositoryInMemory', false],
  ['GemSoftRefCleanupPercentMem', 50],
  ['GemTempObjCacheSize', 149952],
  ['GemTempObjConsecutiveMarksweepLimit', 50],
  ['GemTempObjOomstatsCsv', false],
  ['GemTempObjPomgenScavengeInterval', 1800],
  ['LOG_WARNINGS', true],
  ['SHR_NUM_FREE_FRAME_SERVERS', -1],
  ['SHR_PAGE_CACHE_LARGE_MEMORY_PAGE_POLICY', 0],
  ['SHR_PAGE_CACHE_LARGE_MEMORY_PAGE_SIZE_MB', 0],
  ['SHR_PAGE_CACHE_LOCKED', false],
  ['SHR_PAGE_CACHE_NUM_PROCS', 5105],
  ['SHR_PAGE_CACHE_NUM_SHARED_COUNTERS', 1900],
  ['SHR_PAGE_CACHE_PERMISSIONS', 432],
  ['SHR_PAGE_CACHE_SIZE_KB', 76800000],
  ['SHR_SPIN_LOCK_COUNT', -1],
  ['SHR_TARGET_FREE_FRAME_COUNT', -1],
  ['SHR_WELL_KNOWN_PORT_NUMBER', 0]
])

store.commit('gemsHeader', [
  {text: 'ID', align: 'center', value: 'id'},
  {text: 'Serial', align: 'center', value: 'serial'},
  {text: 'Description', align: 'center', value: 'descr'},
  {text: 'User', align: 'center', value: 'user'},
  {text: 'Host', align: 'center', value: 'host'},
  {text: 'Process', align: 'center', value: 'pid'},
  {text: 'View Age', align: 'center', value: 'viewAge'},
  {text: 'Has Oldest CR', align: 'center', value: 'oldestCR'},
  {text: 'Backlog', align: 'center', value: 'backlog'},
  {text: 'Primitive', align: 'center', value: 'prim'},
  {text: 'State', align: 'center', value: 'state'},
  {text: 'Transaction', align: 'center', value: 'trans'},
  {text: 'Age', align: 'center', value: 'age'},
  {text: 'Quiet Time', align: 'center', value: 'quiet'},
  {text: 'IP', align: 'center', value: 'id'},
  {text: 'Host Id', align: 'center', value: 'hostId'},
  {text: 'Priority', align: 'center', value: 'priority'},
  {text: 'Vote State', align: 'center', value: 'vote'},
  {text: 'Objects', align: 'center', value: 'objects'},
  {text: 'Pages', align: 'center', value: 'pages'},
  {text: 'OOP', align: 'center', value: 'oop'}
])

store.commit('gemsData', [
  {
    oop: 36328961,
    user: 'GcUser',
    pid: 26241,
    host: 'vienna.local',
    prim: 0,
    viewAge: 9250,
    state: 6,
    trans: 0,
    oldestCR: true,
    serial: 1,
    id: 2,
    ip: '::ffff:127.0.0.1',
    priority: 0,
    hostId: 14738033004769738762,
    quiet: 9250,
    age: 91236,
    backlog: 0,
    descr: 'reclaimgcgem',
    objects: 2000,
    pages: 251,
    vote: 2
  },
  {
    oop: 36329217,
    user: 'GcUser',
    pid: 26242,
    host: 'vienna.local',
    prim: 0,
    viewAge: 9246,
    state: 6,
    trans: 0,
    oldestCR: true,
    serial: 2,
    id: 3,
    ip: '::ffff:127.0.0.1',
    priority: 0,
    hostId: 14738033004769738762,
    quiet: 9246,
    age: 91236,
    backlog: 0,
    descr: 'admingcgem',
    objects: 2000,
    pages: 0,
    vote: 2
  },
  {
    oop: 36329473,
    user: 'SymbolUser',
    pid: 26243,
    host: 'vienna.local',
    prim: 0,
    viewAge: 247,
    state: 6,
    trans: 0,
    oldestCR: true,
    serial: 3,
    id: 4,
    ip: '::ffff:127.0.0.1',
    priority: 2,
    hostId: 14738033004769738762,
    quiet: 247,
    age: 91236,
    backlog: 0,
    descr: 'symbolgem',
    objects: 1010,
    pages: 53,
    vote: 2
  },
  {
    oop: 36333057,
    user: 'DataCurator',
    pid: 38810,
    host: 'vienna.local',
    prim: 0,
    viewAge: 7723,
    state: 6,
    trans: 1,
    oldestCR: true,
    serial: 21,
    id: 5,
    ip: '::ffff:192.168.2.129',
    priority: 2,
    hostId: 14738033004769738762,
    quiet: 0,
    age: 15598,
    backlog: 0,
    descr: null,
    objects: 3669,
    pages: 64,
    vote: 2
  }
])
